# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-06 06:05
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delete_time', models.DateTimeField(null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('edit_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='service.BaseModel')),
                ('display_name', models.CharField(max_length=100)),
                ('device_type', models.IntegerField(choices=[(0, 'smart fork'), (1, 'electrocardogram'), (2, 'heart sensor'), (3, 'temperature sensor')])),
                ('status', models.IntegerField(choices=[(0, 'offline'), (1, 'online')])),
                ('home_id', models.IntegerField()),
                ('uuid', models.UUIDField()),
            ],
            bases=('service.basemodel',),
        ),
        migrations.CreateModel(
            name='RawData',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='service.BaseModel')),
                ('data', django.contrib.postgres.fields.jsonb.JSONField()),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.Device')),
            ],
            bases=('service.basemodel',),
        ),
    ]
