# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-08 23:53
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delete_time', models.DateTimeField(null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('edit_time', models.DateTimeField(auto_now=True)),
                ('display_name', models.CharField(max_length=100)),
                ('device_type', models.IntegerField(choices=[(0, 'electrocardiogram'), (1, 'smart fork'), (2, 'body temperature sensor'), (3, 'pill dispenser'), (4, 'stress sensor'), (5, 'exercise activity sensor')])),
                ('status', models.IntegerField(choices=[(0, 'offline'), (1, 'online')])),
                ('home_id', models.IntegerField()),
                ('uuid', models.UUIDField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RawData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delete_time', models.DateTimeField(null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('edit_time', models.DateTimeField(auto_now=True)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField()),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.Device')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
