# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-07 23:58
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delete_time', models.DateTimeField(blank=True, null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('edit_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SaleProduct',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='service.BaseModel')),
                ('display_name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('type', models.IntegerField(choices=[(0, 'patient basic'), (1, 'patient premium'), (2, 'clinic basic'), (3, 'clinic premium')])),
            ],
            bases=('service.basemodel',),
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='service.BaseModel')),
                ('transaction_id', models.UUIDField()),
                ('credit_card_number', models.CharField(max_length=100)),
                ('reference_id', models.CharField(max_length=100)),
                ('amount', models.IntegerField()),
                ('status', models.IntegerField(choices=[(0, 'pending'), (1, 'successful'), (2, 'failed')])),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('bill_address', django.contrib.postgres.fields.jsonb.JSONField()),
                ('order_type', models.IntegerField(choices=[(0, 'patient basic'), (1, 'patient premium'), (2, 'clinic basic'), (3, 'clinic premium')])),
            ],
            bases=('service.basemodel',),
        ),
    ]
